;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-line-text
        c-electric-delete-forward
        c-electric-semi&comma
        c-indent-line-or-region
        caser-camelcase-dwim
        caser-snakecase-dwim
        caser-upper-camelcase-dwim
        counsel-M-x
        default-indent-new-line
        electric-newline-and-maybe-indent
        end-of-buffer
        forward-sexp
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        markdown-outdent-or-delete
        my-backward-delete-word
        my-delete-line
        my-delete-word
        my-smarter-kill-ring-save
        org-beginning-of-line
        org-cycle
        org-cycle-agenda-files
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-metaright
        org-return-and-maybe-indent
        org-self-insert-command
        org-yank
        swiper
        wdired--self-insert
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        open-init-file
        ))
