;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        forward-sexp
        indent-for-tab-command
        kill-region
        my-backward-delete-word
        my-delete-line
        my-delete-word
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ))
