;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-semi&comma
        c-indent-line-or-region
        counsel-M-x
        forward-sexp
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        my-backward-delete-word
        my-delete-line
        my-delete-word
        my-smarter-kill-ring-save
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-return-and-maybe-indent
        org-self-insert-command
        org-yank
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        open-init-file
        ))
